### PR TITLE
Add gallery view file.

### PR DESCRIPTION
**Pull request by Nkozlare**
Hey Nick, this good?

### CODE REVIEW

**Comment by nicholaspix** [comment]
Not good enough

**Comment by CatMo9** [comment]
Hello? Is this even code?

**Comment by Nkozlare** [comment]
I know. I should probably drop out.

**Comment by Nkozlare** [comment]
This was all a joke anyway for anyone reviewing this

**Review by nicholaspix — CHANGES_REQUESTED** [review]
wefdsaf

**Pull request merged**
